on:
 push:
   branches:
     - main
name: Code reviewer
jobs:
  Code-review:
    name: Linter
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name : install estlint and init configs
        run : |
            npm i eslint
            npm init @eslint/config
      - name: Lint Action
        uses: wearerequired/lint-action@v2.3.0
        with:
          eslint: true
          prettier: true

